["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
main = [
    "src/L2Beat.cairo",
]

["protostar.build"]
cairo-path = ["./lib/cairo_contracts/src"]
